# build時に参照できる変数一覧 : https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/build-env-ref-env-vars.html

version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_ACCOUNT_ID - $AWS_REGION - $IMAGE_REPO_NAME - $IMAGE_TAG
      - REPOSITORY_ENDPOINT=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - IMAGE=${REPOSITORY_ENDPOINT}/${IMAGE_REPO_NAME}
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${REPOSITORY_ENDPOINT}
      - echo Commit SHA $CODEBUILD_RESOLVED_SOURCE_VERSION
      - IMAGE_TAG={$CODEBUILD_RESOLVED_SOURCE_VERSION}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ${IMAGE}:${$IMAGE_TAG} .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${IMAGE}:${IMAGE_TAG}
      - echo Writing image definitions file...
      - echo $CONTAINER_NAME - $IMAGE
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE > imageDetail.json
artifacts:
  files: imageDetail.json